Update python-app.yml

diff --git a/.github/workflows/python-app.yml b/.github/workflows/python-app.yml
--- a/.github/workflows/python-app.yml
+++ b/.github/workflows/python-app.yml
@@ -26,13 +26,20 @@ jobs:
         python -m pip install --upgrade pip
         pip install -r requirements.txt
 
+    - name: Ensure Excel file exists
+      run: |
+        if [ ! -f "./Caducidades_Patentes_Europeas_2024.xlsx" ]; then
+          echo "Error: Excel file not found!"
+          exit 1
+        fi
+
     - name: Start FastAPI for testing
       run: |
         uvicorn patentes:app --host 127.0.0.1 --port 8000 --log-level warning &
         sleep 5
       env:
         MONGO_URI: ${{ secrets.MONGO_URI }}
-        EXCEL_PATH: "C:/Users/Raul/Downloads/patentes/Caducidades_Patentes_Europeas_2024.xlsx"
+        EXCEL_PATH: "./Caducidades_Patentes_Europeas_2024.xlsx"
 
     - name: Test FastAPI health endpoint
       run: |
